### ISSUE TITLE
Fetching numbers Error

### ISSUE THREAD

**Issue by davidmrau** [StuWatson/propawhat#6]
I guess due to adding another layer of protection by cloudflare the numbers can't be fetched anymore. Any ideas?

**Comment by StuWatson** [comment]
I think you may be right, I've started getting 403s, I will talk to the 1920.in people see if there is anything we can do

**Comment by davidmrau** [comment]
Another option would be to distribute the numbers directly, which might not be the best in terms of data privacy.

**Comment by dougwithseismic** [comment]
Poll API where possible, hash numbers and dump to additional db as a workaround?

**Comment by StuWatson** [comment]
I don't think I can poll the API because Cloudflares DDoS protection is identifying any programatic request as non human and presenting a Captcha code

**Comment by dougwithseismic** [comment]
> I don't think I can poll the API because Cloudflares DDoS protection is identifying any programatic request as non human and presenting a Captcha code

Workaround land - Would 2captcha donate credits? Can we crowdfund this or another mechanical turk solution? https://2captcha.com/blog/solve-hcaptcha

Might be more effort than worth

**Comment by wojtrze** [comment]
maybe using selenium to open browser and get number would be a solution. Selenium propably doesn't care about protection. It's ugly, I know.

**Comment by StuWatson** [comment]
I got it working with an extension of Selenium called undetected_chromedriver, update coming soon

**Comment by StuWatson** [comment]
Updated to use selenium, see readme for link to selinium install instructions. Try it out and let me know if you have any issues. Remember, your chrome window with Whatsapp Web must be full screen and in the foreground to work (because PyWhatKit uses mouse and keyboard imitation using screen size as reference)
